#!/usr/bin/env bash
# Subly closed-beta participant setup. One run does everything local:
#   deps -> agent key -> buyer env -> (optional) Claude Code MCP registration
# and prints the public key to send to the operator plus the next steps.
#
#   bash demo/setup-beta.sh
#
# Values are prompted, or pre-set via env to skip prompts:
#   SUBLY_CLIENT_API_TOKEN   client token from the operator
#   SOLANA_RPC_URL           your own RPC endpoint (Alchemy/Helius free tier)
#   SUBLY_FACILITATOR_URL    default https://api.demo.sublyfi.com
#   SUBLY_SETUP_SKIP_MCP=1   skip the `claude mcp add` step
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=demo/env/buyer.mainnet.env
KEY_FILE=demo/env/keys/agent-beta.json

echo "== Subly closed-beta setup =="

if [ ! -d node_modules ]; then
  echo "-- installing dependencies (npm ci)"
  npm ci
fi

echo "-- agent wallet key: $KEY_FILE"
PUBKEY=$(npx tsx demo/generate-agent-key.ts "$KEY_FILE")
echo "   public key: $PUBKEY"

if [ -f "$ENV_FILE" ]; then
  echo "-- $ENV_FILE already exists; keeping it (delete it to reconfigure)"
else
  FACILITATOR="${SUBLY_FACILITATOR_URL:-https://api.demo.sublyfi.com}"
  CLIENT_TOKEN="${SUBLY_CLIENT_API_TOKEN:-}"
  RPC_URL="${SOLANA_RPC_URL:-}"
  if [ -z "$CLIENT_TOKEN" ]; then
    printf "client API token (from the operator): "
    read -r CLIENT_TOKEN || true
    if [ -z "$CLIENT_TOKEN" ]; then
      echo "a client token is required (it is in your beta invite)" >&2
      exit 1
    fi
  fi
  if [ -z "$RPC_URL" ]; then
    printf "your Solana RPC URL (empty = public RPC, fine for the beta): "
    read -r RPC_URL || true
    RPC_URL="${RPC_URL:-https://api.mainnet-beta.solana.com}"
  fi
  cat > "$ENV_FILE" <<EOF
# Subly closed-beta buyer env (generated by demo/setup-beta.sh)
export SUBLY_FACILITATOR_URL=$FACILITATOR
export SUBLY_CLIENT_API_TOKEN=$CLIENT_TOKEN
export SOLANA_RPC_URL=$RPC_URL
export SUBLY_DEMO_AGENT_KEYPAIR_PATH=$KEY_FILE
export SUBLY_MCP_MAX_AMOUNT_RAW_USDC=10000
EOF
  chmod 600 "$ENV_FILE"
  echo "-- wrote $ENV_FILE"
fi

if [ "${SUBLY_SETUP_SKIP_MCP:-0}" != "1" ] && command -v claude >/dev/null 2>&1; then
  if claude mcp get subly >/dev/null 2>&1; then
    echo "-- Claude Code MCP server 'subly' already registered"
  else
    claude mcp add subly -- bash "$(pwd)/demo/run-mcp.sh"
    echo "-- registered MCP server 'subly' in Claude Code"
  fi
else
  echo "-- skipped Claude Code MCP registration (claude CLI not found or skipped)"
  echo "   register manually:  claude mcp add subly -- bash \"$(pwd)/demo/run-mcp.sh\""
fi

cat <<EOF

== done. next steps ==
1. send this AGENT PUBLIC KEY to the operator (they register your wallet):
     $PUBKEY
2. send USDC (Solana mainnet) to that address from your wallet
   (no SOL needed; fees are sponsored)
3. deposit into the vault, e.g. 100 USDC:
     source $ENV_FILE && npm run demo:deposit -- 100000000
4. tell the operator you deposited (they activate payments)
5. open a NEW Claude Code session in this repo, approve the 'subly' server,
   and ask it to fetch the paid demo API. Your agent pays from vault yield.

Your private key stays in $KEY_FILE — never share it.
EOF
